apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-fileupload-pvc
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
