apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-v1-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: 69966/earthdx:78
        ports:
        - containerPort: 80
